export const LEADING_PANE_DEFAULT_WIDTH = 316;
export const LEADING_PANE_MAX_WIDTH = 500;
export const LEADING_PANE_MIN_WIDTH = 200;
export const LEADING_PANE_COLLAPSE_WIDTH = 50;

export const TRAILING_PANE_DEFAULT_WIDTH = 250;
export const TRAILING_PANE_MAX_WIDTH = 400;
export const TRAILING_PANE_MIN_WIDTH = 200;
